In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import glob
from tqdm import tqdm
import numpy as np

In [ ]:
# Define path to folder containing CSV files
folder_path = './data'

# Get list of CSV files in the folder
xlsx_files = [file for file in glob.glob(os.path.join(folder_path, "*.xlsx")) if not os.path.basename(file).startswith("~$")]

# Sort CSV files based on date in the filename (assuming MM_DD_YY format)
xlsx_files.sort(key=lambda x: x.split("/")[-1].split(".")[0].split("_")[::-1])

# Create empty dataframe to store combined data
combined_df = pd.DataFrame()

# Read each CSV file and append to combined dataframe
for file in tqdm(xlsx_files, desc="Combining Files"):
    df = pd.read_excel(file, engine='openpyxl')

    time_col = 'time' if 'time' in df.columns else 'Time'

    # Convert 'time' column to datetime format
    df[time_col] = pd.to_datetime(df[time_col], format='%H:%M:%S.%f')

    # Combine 'Date' and time_col columns
    df['DateTime'] = df['Date'] + pd.to_timedelta(df[time_col].dt.time.astype(str))

    combined_df = pd.concat([combined_df, df], ignore_index=True)

In [ ]:
combined_df.to_csv('combined_data.csv')

In [4]:
combined_df = pd.read_csv('combined_data.csv', index_col='DateTime', parse_dates=True)

C:\Users\amoshnin\AppData\Local\Temp\ipykernel_18600\3591635522.py:1: DtypeWarning: Columns (2,35) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.read_csv('combined_data.csv', index_col='DateTime', parse_dates=True)

In [5]:
combined_df

,Date,time,COOLDUTY.0,ES0_TEMP.0,HTR_DUTY.0,SNK_TEMP.0,COOLDUTY.1,ES0_TEMP.1,HTR_DUTY.1,SNK_TEMP.1,...,SNK_TEMP.7,COOLDUTY.2,ES0_TEMP.2,HTR_DUTY.2,SNK_TEMP.2,COOLDUTY.4,ES0_TEMP.4,HTR_DUTY.4,SNK_TEMP.4,Time
DateTime,,,,,,,,,,,,,,,,,,,,,
2024-05-29 15:03:34.208,2024-05-29,1900-01-01 15:03:34.208,0.0,87.7,0.0,24.6,0.0,-99.9,0.0,23.8,...,24.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-29 15:03:38.224,2024-05-29,1900-01-01 15:03:38.224,0.0,87.7,0.0,24.6,0.0,-99.9,0.0,23.8,...,24.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-29 15:03:42.240,2024-05-29,1900-01-01 15:03:42.240,0.0,87.4,0.0,24.7,0.0,-99.9,0.0,23.8,...,24.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-29 15:03:46.255,2024-05-29,1900-01-01 15:03:46.255,0.0,87.4,0.0,24.7,0.0,-99.9,0.0,23.8,...,24.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-29 15:03:50.255,2024-05-29,1900-01-01 15:03:50.255,0.0,87.4,0.0,24.7,0.0,-99.9,0.0,23.8,...,24.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-03 12:00:38.307,2024-08-03,1900-01-01 12:00:38.307,0.0,-1.0,0.0,-99.9,0.0,-1.0,0.0,-99.9,...,-99.9,0.0,-1.0,0.0,-99.9,0.0,-1.0,0.0,-99.9,NaN
2024-08-03 12:00:43.307,2024-08-03,1900-01-01 12:00:43.307,0.0,-1.0,0.0,-99.9,0.0,-1.0,0.0,-99.9,...,-99.9,0.0,-1.0,0.0,-99.9,0.0,-1.0,0.0,-99.9,NaN
2024-08-03 12:00:48.307,2024-08-03,1900-01-01 12:00:48.307,0.0,-1.0,0.0,-99.9,0.0,-1.0,0.0,-99.9,...,-99.9,0.0,-1.0,0.0,-99.9,0.0,-1.0,0.0,-99.9,NaN
2024-08-03 12:00:53.307,2024-08-03,1900-01-01 12:00:53.307,0.0,-1.0,0.0,25.8,0.0,-1.0,0.0,25.0,...,25.1,0.0,-1.0,0.0,25.5,0.0,-1.0,0.0,25.6,NaN
2024-08-03 12:00:58.307,2024-08-03,1900-01-01 12:00:58.307,0.0,-1.0,0.0,25.9,0.0,-1.0,0.0,25.0,...,25.1,0.0,-1.0,0.0,25.5,0.0,-1.0,0.0,25.6,NaN